const Constants={

    Authentication:{
        Getstarted:"Get started with SwiftBel",
        continue:'Continue',
        Login:'Login',
        haveanaccount:'Already have an account?',
        Signupwith:'Sign up with',
        BytappingCreateanAccount:'By tapping Create an Account or Log In, I agree to SwiftBel’s ',
        TermsofService:'Terms of Service, ',
        PaymentsTermsofService:'Payments Terms of Service ',
        And:'and ',
        NondiscriminationPolicy:'Nondiscrimination Policy ',
        acknowledge:'and acknowledge the ',
        PrivacyPolicy:'Privacy Policy.',
        emailforregistration:'Email Sign up:',
        Next:'Next',
        Verifyyouremail:'Verify Your Email',
        EmailSent:'We sent an email to ',
        EmailtoComplete:' If you haven`t recived the verification email, ',
        SpamFolder:'Please check your spam folder.',
        cantfindtheemail:'',
        needHelp:'Need help? ',
        ContactUs:'Contact Us',
        ResendEmail:'Resend Email',
        SetUpPassword:'Create Your Password',
        TypePassword:'Password',
        passwordConfirmation:'Confirm Password',
        Passwordweak:'Password strength: Weak',
        Cantcontainemailaddress:`Can't contain your name or email address`,
        Atleastcharacters:'Atleast 8 characters with one upper case',
        Containssymbol:'Contains a number and symbol',
        Passwordgood:'Password strength: Good',
        Passwordnotmatching:'Password is not matching',
        Welcometo:'Welcome to',
        signUp:'Signup',
        Donthaveanaccount:'Don’t have an account?',
        LogInwith:'Log In with',
        LoginwithMail:"Log in with Mail:",
        password:'Password',
        Createacompanysteps:'Become a Service Provider in 5 steps',
        Letsdoit:'Let’s do it'
    },
    profile:{
        TellUsanameofyourCompany:'What’s the name of your business?',
        Businessname:'Business name *',
        BusinessNumber:'Business Number * ',
        companylocated:'Where is your business located?',
        back:'Back',
        Dragpin:'Drag the map to reposition the pin',
        uploadDoc:'Upload an incorporation document*',
        addPicture:'Add your main profile picture',
        Supprotedformats:'Supproted formats',
        format:'PNG, JPG, PDF',
        FileSize:'File Size',
        maxSize:'Max 5 MB',
        firstName:'First Name',
        lastName:'Last Name',
        AddMoreOwner:'+ Add More Owners',
        BirthProvinceState:'Province of birth',
        BirthCountry:'Country of birth',
        BirthCity:'City of birth',
        Country:'Country of residence',
        Address:'Address',
        ProvinceState :'Province state',
        City:'City',
        PhotooftheID:'Photo of the ID'
    },
    TYPE:{
        registerMail:'REGISTER_MAIL' ,
        registerId:'REGISTER_ID',
        LoginMail:'LOGIN_MAIL',
        createProfile:'CREATE_PROFILE',
        mobileNumber:'MOBILE_NUMBER',
        addService:'ADD_SERVICE',
        addPicture:'ADD_PICTURE',
        addOwner:'ADD_OWNER',
        Businessname:'BUSINESS_NAME',
        addlocation:'ADD_LOCATION',
        authToken:'AUTH_TOKEN',
        address:'ADDRESS',
        profileToken:'PROFILE_TOKEN',
        PostData:'POST_DATA',
        profileDetails:'PROFILE_DETAILS',
        bannerDetails:'BANNER_DETAILS',
        licenseType:'LICENSE_TYPE',
        workerDetails:'WORKER_DETAILS',
        workerMobileNumber:'WORKER_MOBILENUMBER',
        workerPostData:'WORKERPOST_DATA',
        workerprofileDetails:'WORKERPROFILE_DETAILS',
        workerbannerDetails:'WORKERBANNER_DETAILS',
        Workerid:"WORKER_ID",
        workerEmail:'WORKER_EMAIL',
        jobList:'JOB_LIST',
        confirmationNumber:'CONFIRMATION_NUMBER',
        jobdetails:'JOB_DETAILS',
        workerList:"WORKER_DETAILS",
        travelTime:'TRAVEL_TIME',
        userInputDetails:'USER_INPUT_DETAILS',
        summaryDetails:'SUMMARY_DETAILS',
        serviceData:'SERVICES_DATA',
        movingPricedetails:'MOVING_SERVICES_PRICE',
        pressureWashingPriceDetails:'PRESSUREWASHING_PRICE',
        notificationData:'NOTIFICATION_DATA',
        userdetails:'USER_DETAILS'

    }
    
}
export default Constants