export const LOCAL_HOST = "https://prod.swiftbel.com";

export const ServiceEnum = {
    register: "user/register",
    userDetails: "user/userDetails",
    resendVerification: "user/resendVerification",
    setPassword: 'user/setPassword',
    loginUser: 'user/login',
    sendCode: 'twilio/sendCode',
    verifyCode: 'twilio/verify',
    serviceProvider: 'serviceProvider/createAccount',
    gooleSignup: 'user/saveNewGoogleUser',
    appleSignup: 'user/saveNewAppleUser',
    getPost: 'serviceProvider/getPost',
    profileDetails: 'swiftbe',
    useraccountdetails:'user/getUser',
    addNewPost: 'serviceProvider/uploadPost',
    getBannerDetaiils: 'serviceProvider/getImageBanner',
    uploadBannerImage: 'serviceProvider/uploadImageBanner',
    twilioToken: 'twilio/createToken',
    editProfile: 'serviceProvider/editProfile',
    workerProfile: 'worker/completeProfile',
    roofCleaning: 'customer/pressureWashing/editDetails',
    pressureWashing: 'customer/pressureWashing/editDetails',
    editgutterCleaning: 'customer/gutterCleaning/editDetails',
    addNewWorkerPost: 'worker/uploadPost',
    getBannerWorkerDetaiils: 'worker/getCoverPhoto',
    uploadBannerWorkerImage: 'worker/uploadCoverPhoto',
    getWorkerPost: 'worker/getPost',
    workerEditProfile: 'worker/editProfile',
    workerJobs: 'worker/listOfJob',
    stripeIdentity: 'payment/identityVerification',
    getjobDetails: 'worker/getJobDetails',
    materialUpdate: 'booking/addMaterial',
    startJob: 'workerTimer/startTimer',
    oneTimeFee: 'worker/addOneTimeFee',
    finishjob: 'workerTimer/stopTimer',
    workerDetails: 'worker/getWorker',
    getTravelTime: 'worker/getTravelTime',
    saveTravelTime: 'worker/saveTravelTime',
    getStartTime: 'workerTimer/getStartTime',
    summaryDetail: 'worker/detailPage',
    newCreateProfile: 'serviceProvider/v1/createProfile',
    newPasswordSet: 'serviceProvider/v1/setPassword',
    getServices: 'serviceProvider/homePage',
    newSetServices: 'serviceProvider/v1/addServiceOffered',
    getMovingServices: 'movingService/getPrice',
    getPressureWahing: 'pressureWash/getPrice',
    pressureWashingServices: 'pressureWash/enterPrice',
    movingServices: 'movingService/enterPrice',
    getNotificationData: 'serviceProvider/getAllJobs',
    acceptJob: 'serviceProvider/acceptJob',
    inviteWorker: 'serviceProvider/sendInviteLinkToWokers',
    workerList: 'serviceProvider/workerList',
    upcomingjobs: 'serviceProvider/getUpcomingJobs',
    assignedJob: 'serviceProvider/assignJob',
    ongoingJobs: 'serviceProvider/getOnGoingJobs',
    spPersonalDetails: 'certn/details',
    basicProfileDetails: 'user/postUser',
    businessVerification: 'payment/sp/details',
    startTrackingTravelTime: 'workerTimer/startTravelTime',
    stopTrackingTravelTime: 'workerTimer/stopTravelTime',
    getTravelTrackingTime: 'workerTimer/getTravelTime',
    serviceProvideData: 'serviceProvider/listOfJob',
    manageJob: 'serviceProvider/manageJobs',
    fetchAllConvo:'twilio/fetchAllConversation?from=+16042435773',
    FetchConvo:'twilio/fetchConversation',
    sendMessage:'twilio/createConverstaion'

}

export const urlFor = (services) => {
    if (services) {
        return `${LOCAL_HOST}/${services}`
    }
    return undefined;
}